/** @type {import('tailwindcss').Config} */
/** Colors from design token tables (Light scheme). */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Roboto_400Regular'],
        'sans-medium': ['Roboto_500Medium'],
        'sans-bold': ['Roboto_700Bold'],
      },
      colors: {
        primary: '#8c4a60',
        'primary-light': '#ffb1c8',
        'primary-container': '#ffd9e2',
        'on-primary': '#ffffff',
        secondary: '#74565f',
        'secondary-container': '#ffe0e8',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5a3f47',
        tertiary: '#7c5635',
        'tertiary-container': '#ffdcc1',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#623f20',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        background: '#f5f0f0',
        surface: '#fff8f8',
        'surface-container': '#faf2f4',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#22191c',
        'on-surface-variant': '#665459',
        outline: '#837377',
        'outline-variant': '#d5c2c6',
        'frame-stroke': '#e8e7e7',
        accent: '#7c5635',
        'accent-light': '#ffdcc1',
        success: '#27ae60',
        warning: '#e67e22',
        danger: '#ba1a1a',
        'text-primary': '#22191c',
        'text-secondary': '#665459',
        border: '#e8e7e7',
      },
    },
  },
  plugins: [],
};
