import type { PetKindId } from "@/src/constants/pet-kinds";

/**
 * Popular breeds by kind (add pet + edit pet pickers). Keep labels user-facing.
 */
export const BREEDS_BY_KIND: Record<PetKindId, string[]> = {
  Dog: [
    "Mixed breed",
    "Labrador Retriever",
    "Golden Retriever",
    "French Bulldog",
    "German Shepherd",
    "Poodle",
    "Bulldog",
    "Beagle",
    "Rottweiler",
    "Dachshund",
    "Yorkshire Terrier",
    "Australian Shepherd",
    "Cocker Spaniel",
    "Border Collie",
    "Shih Tzu",
    "Boxer",
    "Chihuahua",
    "Siberian Husky",
    "Great Dane",
    "Doberman",
    "Cavalier King Charles Spaniel",
    "Bernese Mountain Dog",
    "Pembroke Welsh Corgi",
    "Maltese",
    "Pug",
    "Boston Terrier",
    "Havanese",
    "English Springer Spaniel",
    "Shetland Sheepdog",
    "Brittany",
    "Vizsla",
    "Weimaraner",
    "Collie",
    "Mastiff",
    "Basset Hound",
    "Saint Bernard",
    "Afghan Hound",
    "Basenji",
    "Akita",
    "Other",
  ],
  Cat: [
    "Mixed / Domestic",
    "Domestic Shorthair",
    "Domestic Longhair",
    "British Shorthair",
    "Persian",
    "Maine Coon",
    "Ragdoll",
    "Siamese",
    "Bengal",
    "Scottish Fold",
    "Sphynx",
    "Norwegian Forest Cat",
    "Russian Blue",
    "American Shorthair",
    "Abyssinian",
    "Birman",
    "Oriental",
    "Devon Rex",
    "Himalayan",
    "Turkish Angora",
    "Other",
  ],
  "Small Furries": [
    "Rabbit",
    "Guinea Pig",
    "Hamster",
    "Gerbil",
    "Rat",
    "Mouse",
    "Chinchilla",
    "Ferret",
    "Hedgehog",
    "Other",
  ],
  Bird: [
    "Budgie / Parakeet",
    "Cockatiel",
    "Lovebird",
    "Canary",
    "Finch",
    "Conure",
    "African Grey",
    "Macaw",
    "Cockatoo",
    "Quaker Parrot",
    "Other",
  ],
  Reptile: [
    "Bearded Dragon",
    "Leopard Gecko",
    "Crested Gecko",
    "Ball Python",
    "Corn Snake",
    "Red-Eared Slider",
    "Russian Tortoise",
    "Blue Tongue Skink",
    "Other",
  ],
  Other: ["Mixed", "Unknown", "Other"],
};
